apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEEyTVRJeQpNVE0zTVRoYUZ3MDBOVEEyTVRJeU1UTTNNVGhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMEQ0YUE5UFdqaEFrT09pTmlLRk9CZzdRVHJ5YkdzWXZjcU5zU2Zobi9EVytZSDBxMgpQa0c1aTRDeDBLN2YvakZuNEkvRFhMZVFSMWFKVENEWVZkQk5LUGN0ZGRLRTJjT0liTW5kL1h0VHliUTh3aHJSCkYxZjN6d3haRHJqMXovYkFrMFR4UHJGNGxYWCsrejRsNzhIUURNMzhkQ29JUm1RbXVkL2tTajlZSllUVExpU3UKaEwrNXlQT2hZR3JweDNxSkZVK2pGdHI0ZVdEMC9PWjlOR3dTK1hab0ZnU3JQWmxPS1A1OFRJekN5SnpJaUl2awpGMzZ2QTBiVmdMNXdldTd4ZHFtWXVYK0hpWmdPckM1REZYcDludDVCeGlIWlJjVFFZdEZTalBuYjUrQ3paSVlWCnY2K2EveEZ6VDRKZkh4TVNRQjA2RmZZa29OdlMzNDV4Q0w3SkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJVMWU3bHozZTNQazROZ2lGOAo3dUJCditmVFFEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtVXQwTnhyYWhmTDlwd1RXcW1yd3E5TDkwQk9kCmk1MTNZSHR5UUkwODZYZG1UaHUvS3g4M08ycCtkVGN1MlN0cVJZMmNld21lRTFWMEpLV1BSdG1pc09lTFJRbHUKZTNJa1hHYlJHT0cwTzZkMlBEWFFVRGhvVmQ4UGhLMTJXMnBpWTVwam03RHYrZ0JhL1BDT0VnR2N4SGl2dmFPegpzMUdEK3YvdTRNemxMWFVVYkJuU1BhMFBjZzhTL04xbm1SWGNHQXNVWFlpQmxjZkxLOWNKZE90UlhYVS8zTXlECkdKa2pNOEx4anFnZndrb0htOGRmYmxwaHoyY3Nya0poMWxwT0daNUhPSFI4M3pvQUxUZ01Id04zZmxlSW50Q2oKZXVtNjlYRXR6Slo1UThJd3RnVmRGL1FzM3l2RWRqZ0tHa1Y1QnhIME9kZ3NOL09pZnZPRHpoYkdDdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://55f780d5-845b-4c95-b449-3574522b5ec6.k8s.ondigitalocean.com
  name: do-sgp1-k8s-1-32-2-do-3-sgp1-1749764162102
contexts:
- context:
    cluster: do-sgp1-k8s-1-32-2-do-3-sgp1-1749764162102
    user: do-sgp1-k8s-1-32-2-do-3-sgp1-1749764162102-admin
  name: do-sgp1-k8s-1-32-2-do-3-sgp1-1749764162102
current-context: do-sgp1-k8s-1-32-2-do-3-sgp1-1749764162102
kind: Config
preferences: {}
users:
- name: do-sgp1-k8s-1-32-2-do-3-sgp1-1749764162102-admin
  user:
    token: dop_v1_90588199871d96979ca56ca6e37ca7f6bedbd1aea587a394c73cafbaea0f056f
