apiVersion: v1
kind: Service
metadata:
  name: password-strength-service
spec:
  selector:
    app: password-strength
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
